### ISSUE TITLE
filter headers that are forbidden by nodejs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-dispatch#432]
dispatch forwards all client request headers, which cause problems in by nodejs:
```

{
   "level"  :  "error" ,
   "ow"  : {
     "activationId"  :  "78405b31-b1ea-4724-9a93-be97b8a4965d" ,
     "actionName"  :  "helix-services--dispatch@88" ,
     "transactionId"  :  "Root=1-603dd4b9-613269ad083dcdc900ab0614;Parent=47a084130744b434;Sampled=0" 
  },
   "params"  : {},
   "error"  : {
     "$type"  :  "NodeError" ,
     "name"  :  "TypeError" ,
     "message"  :  "HTTP/1 Connection specific headers are forbidden: \"proxy-connection\"" ,
     "stack"  :  "TypeError [ERR_HTTP2_INVALID_CONNECTION_HEADERS]: HTTP/1 Connection specific headers are forbidden: \"proxy-connection\"
    at mapToHeaders (internal/http2/util.js:505:13)
    at ClientHttp2Session.request (internal/http2/core.js:1673:25)
    at /var/task/index.js:7686:19
    at new Promise (<anonymous>)
    at Object.request (/var/task/index.js:7587:10)
    at request (/var/task/index.js:8170:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)" ,
     "code"  :  "ERR_HTTP2_INVALID_CONNECTION_HEADERS" 
  },
```

**Comment by tripodsan** [comment]
using this list:
https://github.com/nodejs/node/blob/1b4790b243fc9616c5c74f056f2100c4f0a20108/lib/internal/http2/util.js#L423-L438
